INSERT INTO unidades_medida (empresa_id, codigo, nombre, abreviatura, activo) VALUES
(?, 'UN', 'Unidad', 'UN', 1),
(?, 'LB', 'LIBRA', 'LB', 1),
(?, 'KG', 'Kilogramo', 'kg', 1),
(?, 'GR', 'Gramo', 'gr', 1),
(?, 'MG', 'Miligramo', 'mg', 1),
(?, 'TON', 'Tonelada', 't', 1),
(?, 'LIBRA', 'Libra', 'libra', 1),
(?, 'OZ', 'Onza', 'oz', 1),
(?, 'ONZA', 'Onza', 'onza', 1),
(?, 'TON_US', 'Tonelada US', 'ton US', 1),
(?, 'QQ', 'Quintal', 'qq', 1),
(?, 'L', 'Litro', 'L', 1),
(?, 'LT', 'Litro', 'lt', 1),
(?, 'LITRO', 'Litro', 'litro', 1),
(?, 'ML', 'Mililitro', 'ml', 1),
(?, 'M3', 'Metro cúbico', 'm³', 1),
(?, 'PT', 'Pinta', 'pt', 1),
(?, 'FL_OZ', 'Onza fluida', 'fl oz', 1),
(?, 'M', 'Metro', 'm', 1),
(?, 'MT', 'Metro', 'mt', 1),
(?, 'METRO', 'Metro', 'metro', 1),
(?, 'MM', 'Milímetro', 'mm', 1),
(?, 'KM', 'Kilómetro', 'km', 1),
(?, 'FT', 'Pie', 'ft', 1),
(?, 'PIE', 'Pie', 'pie', 1),
(?, 'IN', 'Pulgada', 'in', 1),
(?, 'PULGADA', 'Pulgada', 'pulgada', 1),
(?, 'YD', 'Yarda', 'yd', 1),
(?, 'MI', 'Milla', 'mi', 1),
(?, 'M2', 'Metro cuadrado', 'm²', 1),
(?, 'KM2', 'Kilómetro cuadrado', 'km²', 1),
(?, 'HA', 'Hectárea', 'ha', 1),
(?, 'FT2', 'Pie cuadrado', 'ft²', 1),
(?, 'IN2', 'Pulgada cuadrada', 'in²', 1),
(?, 'TAREA', 'Tarea', 'tarea', 1),
(?, 'UND', 'Unidad', 'und', 1),
(?, 'UNIDAD', 'Unidad', 'unidad', 1),
(?, 'PZ', 'Pieza', 'pz', 1),
(?, 'PIEZA', 'Pieza', 'pieza', 1),
(?, 'MIL', 'Millar', 'millar', 1),
(?, 'PAR', 'Par', 'par', 1),
(?, 'SAC', 'Saco', 'saco', 1),
(?, 'PAQ', 'Paquete', 'paq', 1),
(?, 'FRA', 'Frasco', 'frasco', 1),
(?, 'LAT', 'Lata', 'lata', 1),
(?, 'TUB', 'Tubo', 'tubo', 1),
(?, 'ROL', 'Rollo', 'rollo', 1),
(?, 'H', 'Hora', 'h', 1),
(?, 'MIN', 'Minuto', 'min', 1),
(?, 'SEM', 'Semana', 'sem', 1),
(?, 'MES', 'Mes', 'mes', 1);
