CREATE TABLE IF NOT EXISTS pagos_plataforma (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    empresa_id INT NULL,
    cliente_nombre VARCHAR(255) NOT NULL,
    cliente_email VARCHAR(255) NULL,
    cliente_telefono VARCHAR(30) NULL,
    negocio_nombre VARCHAR(255) NOT NULL,
    concepto VARCHAR(255) NOT NULL,
    descripcion TEXT NULL,
    moneda CHAR(3) NOT NULL DEFAULT 'DOP',
    monto DECIMAL(14,2) NOT NULL,
    descuento DECIMAL(14,2) NOT NULL DEFAULT 0,
    impuestos DECIMAL(14,2) NOT NULL DEFAULT 0,
    metodo_pago VARCHAR(50) NOT NULL,
    referencia VARCHAR(120) NULL,
    fecha_pago DATETIME NOT NULL,
    estado ENUM('pending','confirmed','rejected') NOT NULL DEFAULT 'pending',
    confirmado_por INT NULL,
    fecha_confirmacion DATETIME NULL,
    rechazado_por INT NULL,
    fecha_rechazo DATETIME NULL,
    motivo_rechazo TEXT NULL,
    invoice_status ENUM('pending','generated','failed') NOT NULL DEFAULT 'pending',
    invoice_error TEXT NULL,
    whatsapp_status ENUM('not_requested') NOT NULL DEFAULT 'not_requested',
    email_status ENUM('pending','sent','failed') NOT NULL DEFAULT 'pending',
    email_error TEXT NULL,
    fecha_ultimo_email DATETIME NULL,
    creado_por INT NOT NULL,
    fecha_creacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_pagos_plataforma_estado_fecha (estado, fecha_pago),
    KEY idx_pagos_plataforma_empresa (empresa_id),
    KEY idx_pagos_plataforma_cliente (cliente_nombre),
    KEY idx_pagos_plataforma_metodo (metodo_pago),
    CONSTRAINT fk_pagos_plataforma_empresa FOREIGN KEY (empresa_id) REFERENCES empresas(id) ON DELETE SET NULL,
    CONSTRAINT fk_pagos_plataforma_confirmado_por FOREIGN KEY (confirmado_por) REFERENCES usuarios(id) ON DELETE SET NULL,
    CONSTRAINT fk_pagos_plataforma_rechazado_por FOREIGN KEY (rechazado_por) REFERENCES usuarios(id) ON DELETE SET NULL,
    CONSTRAINT fk_pagos_plataforma_creado_por FOREIGN KEY (creado_por) REFERENCES usuarios(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS facturas_plataforma (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    pago_id BIGINT UNSIGNED NOT NULL,
    numero_factura VARCHAR(30) NOT NULL,
    archivo_pdf VARCHAR(500) NULL,
    estado ENUM('pending','generated','failed') NOT NULL DEFAULT 'pending',
    error_generacion TEXT NULL,
    fecha_emision DATETIME NULL,
    fecha_creacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_facturas_plataforma_pago (pago_id),
    UNIQUE KEY uk_facturas_plataforma_numero (numero_factura),
    CONSTRAINT fk_facturas_plataforma_pago FOREIGN KEY (pago_id) REFERENCES pagos_plataforma(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS pagos_plataforma_auditoria (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    pago_id BIGINT UNSIGNED NOT NULL,
    admin_user_id INT NOT NULL,
    accion VARCHAR(60) NOT NULL,
    estado_anterior VARCHAR(30) NULL,
    estado_nuevo VARCHAR(30) NULL,
    motivo TEXT NULL,
    fecha_creacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_pagos_plataforma_auditoria_pago (pago_id, fecha_creacion),
    CONSTRAINT fk_pagos_plataforma_auditoria_pago FOREIGN KEY (pago_id) REFERENCES pagos_plataforma(id) ON DELETE CASCADE,
    CONSTRAINT fk_pagos_plataforma_auditoria_admin FOREIGN KEY (admin_user_id) REFERENCES usuarios(id) ON DELETE RESTRICT
);