// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = never
type AppRouteHandlerRoutes = "/api/catalogo-superadmin/[slug]/config" | "/api/catalogo-superadmin/[slug]/pedido" | "/api/catalogo-superadmin/[slug]/producto/[id]" | "/api/catalogo-superadmin/[slug]/productos" | "/api/catalogo/[slug]/config" | "/api/catalogo/[slug]/pedido" | "/api/catalogo/[slug]/producto/[id]" | "/api/catalogo/[slug]/productos" | "/api/clientes/[clienteId]/historial" | "/api/clientes/[clienteId]/pagos" | "/api/contratos/[id]/pdf" | "/api/contratos/enviar-email" | "/api/contratos/notificaciones" | "/api/copyright" | "/api/datos-admin" | "/api/debug/chunks" | "/api/debug/schema" | "/api/financiamiento/alertas" | "/api/financiamiento/contratos" | "/api/financiamiento/contratos/[id]" | "/api/financiamiento/pagos" | "/api/financiamiento/planes" | "/api/login" | "/api/manifest" | "/api/modulos" | "/api/modulos/verificar" | "/api/movil/descargar" | "/api/movil/login" | "/api/movil/ponerOnline" | "/api/movil/subir" | "/api/printer/config" | "/api/printer/cut" | "/api/printer/drawer" | "/api/printer/print" | "/api/printer/test" | "/api/productos/importar" | "/api/productos/importar/estado/[jobId]" | "/api/productos/procesar" | "/api/productos/upload" | "/api/productos/upload/chunk" | "/api/qz-certificate" | "/api/qz-sign" | "/api/superadmin/pagos/[id]/factura" | "/api/sync/status" | "/api/upload-video" | "/api/ventas/[id]" | "/api/ventas/sync" | "/api/whatsapp/enviar-perfil-cliente"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/sucursales" | "/superadmin" | "/vendedor"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/api/catalogo-superadmin/[slug]/config": { "slug": string; }
  "/api/catalogo-superadmin/[slug]/pedido": { "slug": string; }
  "/api/catalogo-superadmin/[slug]/producto/[id]": { "slug": string; "id": string; }
  "/api/catalogo-superadmin/[slug]/productos": { "slug": string; }
  "/api/catalogo/[slug]/config": { "slug": string; }
  "/api/catalogo/[slug]/pedido": { "slug": string; }
  "/api/catalogo/[slug]/producto/[id]": { "slug": string; "id": string; }
  "/api/catalogo/[slug]/productos": { "slug": string; }
  "/api/clientes/[clienteId]/historial": { "clienteId": string; }
  "/api/clientes/[clienteId]/pagos": { "clienteId": string; }
  "/api/contratos/[id]/pdf": { "id": string; }
  "/api/contratos/enviar-email": {}
  "/api/contratos/notificaciones": {}
  "/api/copyright": {}
  "/api/datos-admin": {}
  "/api/debug/chunks": {}
  "/api/debug/schema": {}
  "/api/financiamiento/alertas": {}
  "/api/financiamiento/contratos": {}
  "/api/financiamiento/contratos/[id]": { "id": string; }
  "/api/financiamiento/pagos": {}
  "/api/financiamiento/planes": {}
  "/api/login": {}
  "/api/manifest": {}
  "/api/modulos": {}
  "/api/modulos/verificar": {}
  "/api/movil/descargar": {}
  "/api/movil/login": {}
  "/api/movil/ponerOnline": {}
  "/api/movil/subir": {}
  "/api/printer/config": {}
  "/api/printer/cut": {}
  "/api/printer/drawer": {}
  "/api/printer/print": {}
  "/api/printer/test": {}
  "/api/productos/importar": {}
  "/api/productos/importar/estado/[jobId]": { "jobId": string; }
  "/api/productos/procesar": {}
  "/api/productos/upload": {}
  "/api/productos/upload/chunk": {}
  "/api/qz-certificate": {}
  "/api/qz-sign": {}
  "/api/superadmin/pagos/[id]/factura": { "id": string; }
  "/api/sync/status": {}
  "/api/upload-video": {}
  "/api/ventas/[id]": { "id": string; }
  "/api/ventas/sync": {}
  "/api/whatsapp/enviar-perfil-cliente": {}
  "/sucursales": {}
  "/superadmin": {}
  "/vendedor": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/sucursales": never
  "/superadmin": never
  "/vendedor": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
